name: Environment Example

on:
  workflow_dispatch:

jobs:
  entry_job:
    runs-on: ubuntu-latest
    steps:
      - name: Entry Job
        run: |
          echo "woah i am the entry job, i don't do anything interesting so i need no environment!"

  parallel_job_1:
    permissions:
      contents: "read"
      id-token: "write" # Required for WIF authentication
    needs: entry_job
    uses: ./.github/workflows/simple-example.yaml
    with:
      environment: example-environment

  parallel_job_2:
    permissions:
      contents: "read"
      id-token: "write" # Required for WIF authentication
    needs: entry_job
    uses: ./.github/workflows/simple-example.yaml
    with:
      environment: example-environment
