name: Environment Example

on:
  workflow_dispatch:

jobs:
  entry_job:
    runs-on: ubuntu-latest
    steps:
      - name: Entry Job
        run: |
          echo "woah i am the entry job, i don't do anything interesting so i need no environment!"

  parallel_job_1:
    environment: example-environment
    uses: ./.github/workflow/simple-example.yaml
    
  parallel_job_2:
    environment: example-environment
    uses: ./.github/workflow/simple-example.yaml
